/**********************************************************************************************************************
 * \file mp3.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <Mp3.h>
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "IfxAsclin_Asc.h"
#include "Bsp.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define Start_Byte 0x7E // 시작 값
#define Version_Byte 0xFF // 버전 값
#define Command_Length 0x06 // 길이 값
#define End_Byte 0xEF // 종료 값
#define Acknowledge 0x00 // 피드백 미 수신

#define CMD_Specify_num 0x03 // 특정 번호 음악 재생
#define CMD_Next 0x01 // 다음 곡 재생
#define CMD_Previous 0x02 // 이전 곡 재생
#define CMD_Increase_Volume 0x04 // 볼륨 업
#define CMD_Decrease_Volume 0x05 // 볼륨 다운
#define CMD_Specify_Volume 0x06 // 특정 볼륨 설정
#define CMD_Specify_playback_mode 0x08 // 반복 모드 설정
#define CMD_Repeat_set 0x11 // 반복 모드 설정
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
uint16 Get_Checksum(uint8 input_cmd, uint8 parameter1, uint8 parameter2);

void Mp3_Init(){
    Asclin2_Init();
}
uint16 Get_Checksum(uint8 input_cmd, uint8 parameter1, uint8 parameter2){
    return -(Version_Byte + Command_Length + input_cmd + Acknowledge + parameter1 + parameter2);
}
void Mp3_Volume_Up(){
    uint16 checksum = Get_Checksum(CMD_Decrease_Volume, 0x00,0x00);
    uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Decrease_Volume, Acknowledge, 0x00, 0x00, ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
    Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
void Mp3_Volume_Down(){
    uint16 checksum = Get_Checksum(CMD_Increase_Volume, 0x00,0x00);
        uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Increase_Volume, Acknowledge, 0x00, 0x00, ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
        Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
void Mp3_Volume_Set(uint8 volume){
    uint16 checksum = Get_Checksum(CMD_Specify_Volume, 0x00,volume);
    uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Specify_Volume, Acknowledge, 0x00, volume, ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
    Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
void Mp3_Next_Music(){
    uint16 checksum = Get_Checksum(CMD_Next, 0x00,0x00);
    uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Next, Acknowledge, 0x00, 0x00, ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
    Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
void Mp3_Prev_Music(){
    uint16 checksum = Get_Checksum(CMD_Previous, 0x00,0x00);
    uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Previous, Acknowledge, 0x00, 0x00, ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
    Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
void Mp3_Music_Set(uint16 music_num){
    uint16 checksum = Get_Checksum(CMD_Specify_num, ((music_num >> 8) & 0xFF),(music_num & 0xFF));
    uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Specify_num, Acknowledge, ((music_num >> 8) & 0xFF), (music_num & 0xFF), ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
    Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
void Mp3_Single_Repeat(){
    uint16 checksum = Get_Checksum(CMD_Specify_playback_mode, 0x00,0x02);
    uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Specify_playback_mode, Acknowledge, 0x00, 0x02, ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
    Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
void Mp3_Repeat(){
    uint16 checksum = Get_Checksum(CMD_Specify_playback_mode, 0x00,0x00);
    uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Specify_playback_mode, Acknowledge, 0x00, 0x00, ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
    Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
void Mp3_Random(){
    uint16 checksum = Get_Checksum(CMD_Specify_playback_mode, 0x00,0x03);
    uint8 Serial_Bytes[10] = { Start_Byte, Version_Byte, Command_Length, CMD_Specify_playback_mode, Acknowledge, 0x00, 0x03, ((checksum >> 8) & 0xFF), (checksum & 0xFF), End_Byte };
    Send_Bytes(Serial_Bytes, sizeof(Serial_Bytes));

}
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
